openapi: 3.0.0
info:
  title: YouSay API Docs
  version: 0.1.0
  description: This is a simple CRUD API application made with Express and documented with Swagger
servers:
  - url: http://localhost:8080/
paths:
  /polls:
    post:
      summary: Create a new poll
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Poll"
      responses:
        201:
          description: New poll created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Poll"
        500:
          $ref: "#/components/responses/ResponseUnknownError"
  /polls/{slug}:
    get:
      summary: Get a single poll by slug
      parameters:
        - name: slug
          in: path
          description: Poll's url path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Poll successfully fetched.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Poll"
        404:
          $ref: "#/components/responses/ResponseNotFound"
        500:
          $ref: "#/components/responses/ResponseUnknownError"
components:
  schemas:
    Poll:
      type: object,
      properties:
        title:
          type: string,
        status:
          type: string,
          enum: [draft, active, completed]
        slug:
          type: string,
      example:
        title: The poll's title
        status: active
        slug: the-poll-url
    ResponseGeneralError:
      type: object
      properties:
        msg:
          type: string
  responses:
    ResponseNotFound:
      description: Resource not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseGeneralError"
    ResponseUnknownError:
      description: Unknown error has occured.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseGeneralError"
            example:
              msg: Something went wrong.